### ISSUE TITLE
Cannot use certain characters while typing

### ISSUE THREAD

**Issue by App24** [Minivera/FocusTreeAndEventManager#18] opened 2017-04-10 15:06 UTC
While trying to code, I put a '{' or '}' or '=' and gives this error
![capture](https://cloud.githubusercontent.com/assets/25138297/24868318/96a6d796-1e07-11e7-9e86-adf477c1484e.PNG)

**Comment by Minivera** [comment] 2017-04-12 15:46
This is caused by the code editor checking after EVERY key press if the script can be parsed. The parser is meant to throw an exception if the code has syntax errors (Not closing brackets for example), hence the .First rather than .FirstOrDefault. 

Beta_3_a will change the parsing check after return is pressed and will change the InvalidOperationException to a syntax error, preventing any crashes. You can try it in the beta_3_a branch.

I'm leaving this issue open until release.

**Closed** 2017-04-24 19:51 UTC
